baseURL = "https://juliabielsa.com/"
languageCode = "es-es"
title = "Bottom-Up Cybersecurity"
theme = "PaperMod"
author = "Julia Bielsa"
[params]
  defaultTheme = "auto"
  ShowAuthor = true
  ShowReadingTime = true

  [params.homeInfoParams]
    Title = "Julia Bielsa"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/julia-bielsa-22b65010b/"